name: dev
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - cryptography=41.0.7
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - idna=3.4
  - jinja2=3.1.2
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.3.0
  - openssl=3.0.12
  - pillow=10.0.1
  - pip=23.3.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.7
  - pytorch=2.2.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tk=8.6.12
  - torchaudio=2.2.0
  - torchvision=0.17.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - attrs==23.2.0
    - av==11.0.0
    - bitsandbytes==0.42.0
    - click==8.1.7
    - contourpy==1.2.0
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - docstring-parser==0.15
    - einops==0.7.0
    - fonttools==4.47.2
    - frozenlist==1.4.1
    - fsspec==2023.12.2
    - gitdb==4.0.11
    - gitpython==3.1.41
    - huggingface-hub==0.20.3
    - hydra-core==1.3.2
    - imageio-ffmpeg==0.4.9
    - importlib-resources==6.1.1
    - jsonargparse==4.27.4
    - kiwisolver==1.4.5
    - lightning==2.1.3
    - lightning-utilities==0.10.1
    - markdown-it-py==3.0.0
    - matplotlib==3.8.2
    - mdurl==0.1.2
    - multidict==6.0.4
    - omegaconf==2.3.0
    - opencv-python==4.9.0.80
    - packaging==23.2
    - positional-encodings==6.0.3
    - protobuf==4.25.2
    - psutil==5.9.8
    - pygments==2.17.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytorch-lightning==2.1.3
    - rich==13.7.0
    - safetensors==0.4.2
    - scipy==1.12.0
    - sentry-sdk==1.39.2
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - tensorboardx==2.6.2.2
    - timm==0.9.12
    - torchmetrics==1.3.0.post0
    - tqdm==4.66.1
    - typeshed-client==2.4.0
    - wandb==0.16.2
    - x-transformers==1.27.14
    - yarl==1.9.4
