seed_everything: 42

model:
  class_path: models.align.Align
  init_args:
    dim: 768
    resolution: [224, 224]
    n_slots: 3
    n_img_slots: 3
    n_txt_slots: 3
    font_path: "Arial.ttf"
    optimizer: adamw
    optimizer_args:
      lr: 2e-4
      weight_decay: 1e-2
    image_encoder_name: 'vit_base_patch14_reg4_dinov2.lvd142m'
    slot_attention_arch: sat
    slot_attention_args:
      input_dim: ${..dim}
      slot_dim: ${..dim}
      depth: 1
      n_iters: 5
      implicit: True
    feature_decoder_args:
      dim: ${..dim}
      depth: 4

data:
  class_path: dataset.coco.COCOCap
  init_args:
    root_dir: ./data/coco
    num_workers: 7
    batch_size: 16
    resolution: 224

trainer:
  accelerator: mps
  accumulate_grad_batches: 4
  # logger: 
  #   class_path: lightning.pytorch.loggers.WandbLogger
  #   init_args:
  #     project: "align"
  #     save_dir: ./lightning_logs
  val_check_interval: 0.01
  limit_val_batches: 1
  log_every_n_steps: 5
