seed_everything: 42

model:
  class_path: models.compositional_jepa.CompositionalJEPA
  init_args:
    dim: 384 
    resolution: [448, 448]
    shrink_factors: [1, 4, 4]
    n_slots: [16, 16, 8]
    max_seq_lens: [10, 20, 20]
    schedule: 
      - start_step: 0
        t_max: 64
        train: [True, False, False]
        skip: [False, True, True]
      - start_step: 2000
        t_max: 64
        train: [True, True, False]
        skip: [False, False, True]
      - start_step: 4000
        t_max: 64
        train: [True, True, True]
        skip: [False, False, False]
    image_encoder_name: 'vit_small_patch14_reg4_dinov2.lvd142m'
    optimizer: adamw
    optimizer_args:
      lr: 3e-4
    loss_args:
      loss: "sinkhorn"
      p: 2
      blur: 0.05
      scaling: 0.5
    slot_attention_args:
      input_dim: ${..dim}
      slot_dim: ${..dim}
      sampler: "gaussian_dependent"
      n_iters: 8
      implicit: True
    encoder_args:
      dim: ${..dim}
      depth: 4
      ff_glu: True
      ff_swish: True
      attn_flash: True
    predictor_args:
      dim: ${..dim}
      depth: 4
      ff_glu: True
      ff_swish: True
      attn_flash: True
    decoder_args:
      dim: ${..dim}
      depth: 4
      ff_glu: True
      ff_swish: True
      attn_flash: True
      cross_attend: True

# data:
#   class_path: dataset.clevrer.CLEVRER
#   init_args:
#     data_dir: ./data/clevrer
#     n_frames: 25
#     stride: 2
#     num_workers: 8
#     batch_size: 16
#     resolution: 448

data:
  class_path: dataset.ucf.UCF
  init_args:
    ucf_config:
      root: ./data/ucf/UCF-101
      annotation_path: ./data/ucf/ucfTrainTestlist
      frames_per_clip: 64
      # step_between_clips: 5
      frame_rate: 8
      num_workers: 16
      output_format: "TCHW"
    loader_config:
      num_workers: 6
      batch_size: 6
      shuffle: True
    resolution: 448

trainer:
  accumulate_grad_batches: 4
  precision: "bf16-mixed"
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "comp_jepa"
      log_model: False
      save_dir: ./lightning_logs
  val_check_interval: 0.02
  limit_val_batches: 1
  log_every_n_steps: 25
