seed_everything: 42

model:
  class_path: models.compositional_jepa.CompositionalJEPA
  init_args:
    dim: 384 
    resolution: [224, 224]
    n_slots: 8
    image_encoder_name: 'vit_small_patch14_reg4_dinov2.lvd142m'
    optimizer: adamw
    optimizer_args:
      lr: 2e-4
      weight_decay: 1e-2
    slot_attention_args:
      input_dim: 384
      slot_dim: 384
      sampler: "gaussian"
      n_iters: 5
      implicit: True
    predictor_args:
      dim: ${..dim}
      depth: 4
      ff_glu: True
      ff_swish: True

data:
  class_path: dataset.clevrer.CLEVRER
  init_args:
    data_dir: ./data/clevrer
    n_frames: 10
    stride: 10
    num_workers: 7
    batch_size: 8
    resolution: 224

trainer:
  accumulate_grad_batches: 8
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "comp_jepa"
      save_dir: ./lightning_logs
  val_check_interval: 0.003
  limit_val_batches: 8
  log_every_n_steps: 5
