seed_everything: 42

model:
  class_path: model.jepa.EMAJEPA
  init_args:
    dim: 64
    n_frames: 5
    ema_alpha: 0.996
    max_slots: 8
    min_slots: 7
    learning_rate: 1e-3
    base_model: 
      class_path: model.jepa.SlotJEPA
      init_args:
        dim: ${...dim}
        n_frames: ${...n_frames}
        max_slots: ${...max_slots}
        decoder_depth: 3
        predictor_depth: 4
        fixed_point_iterations: 5
        backbone:
          class_path: model.encoder.ResNetEncoder
          init_args:
            dim: ${.....dim}
            depth: 4
    decoder:
      class_path: model.decoder.SpatialBroadcastDecoder
      init_args:
        dim: ${...dim}
        depth: 6
        init_resolution: [8, 8]
    decoder_detach: True

data:
  class_path: dataset.clevrer.CLEVRER
  init_args:
    data_dir: ./data/clevrer
    num_workers: 7
    n_frames: ${model.init_args.n_frames}
    batch_size: 2
    resolution: 128

trainer:
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "semdec"
      save_dir: ./lightning_logs
  log_every_n_steps: 50
