seed_everything: 42

model:
  class_path: model.jepa.EMAJEPA
  init_args:
    dim: 64
    n_frames: 25
    ema_alpha: 0.996
    max_slots: 10
    min_slots: 3
    learning_rate: 1e-3
    base_model: 
      class_path: model.jepa.SlotJEPA
      init_args:
        dim: ${...dim}
        n_frames: ${...n_frames}
        max_slots: ${...max_slots}
        backbone: resnet18.a1_in1k
        pretrained_backbone: True
        feature_level: 2
        decoder_depth: 1
        predictor_depth: 4
        fixed_point_iterations: 5
    # decoder:
    #   class_path: model.decoder.SpatialBroadcastDecoder
    #   init_args:
    #     dim: ${...dim}
    #     depth: 3
    #     resolution: ${data.init_args.resolution}
    # decoder_detach: True

data:
  class_path: dataset.clevrer.CLEVRER
  init_args:
    data_dir: ./data/clevrer
    num_workers: 7
    n_frames: ${model.init_args.n_frames}
    batch_size: 8
    resolution: [64, 96]

trainer:
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "semdec"
  log_every_n_steps: 50
