seed_everything: 42

model:
  class_path: models.jepa.EMAJEPA
  init_args:
    dim: 64
    ema_alpha: 0.996
    learning_rate: 5e-4
    base_model: 
      class_path: models.jepa.SlotJEPA
      init_args:
        image_encoder:
          class_path: models.encoder.ResNetEncoder
          init_args:
            dim: ${.....dim}
            depth: 4
        slot_attention:
          class_path: models.slot_attention.ISARecurrent
          init_args:
            input_dim: ${.....dim}
            slot_dim: ${.....dim}
            n_iters: 4
            n_slots: 7
        dim: ${...dim}
        predictor_depth: 4
    decoder:
      class_path: models.decoder.SpatialBroadcastDecoder
      init_args:
        dim: ${...dim}
        depth: 6
        init_resolution: [8, 8]
    decoder_detach: True
    decoder_start_epoch: 3

data:
  class_path: dataset.clevrer.CLEVRER
  init_args:
    data_dir: ./data/clevrer
    num_workers: 7
    n_frames: 20
    batch_size: 1
    resolution: 128

trainer:
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "semdec"
      save_dir: ./lightning_logs
  log_every_n_steps: 3
