seed_everything: 42

model:
  class_path: models.interpreter_image.InterpreterTrainer
  init_args:
    base_config:
        model_name: 'vit_base_patch14_reg4_dinov2.lvd142m'
        resolution: [448, 448]
    # active_block: 0
    block_configs:
      - dim: 768
        slot_dim: 768
        n_slots: 32
        dec_depth: 4 
    optimizer_config:
      start_lr: 1e-4
      ref_lr: 3e-4
      final_lr: 2e-6
      warmup_epochs: 5
      weight_decay: 0.05

data:
  class_path: dataset.coco.COCOSeg
  init_args:
    data_dir: ./data/coco/images
    ann_dir: ./data/coco/annotations/annotations/
    num_workers: 12
    batch_size: 64
    resolution: 448

trainer:
  accumulate_grad_batches: 1
  precision: "bf16-mixed"
  # logger:
  #   class_path: lightning.pytorch.loggers.WandbLogger
  #   init_args:
  #     project: "comp_jepa"
  #     log_model: False
  #     save_dir: ./lightning_logs
  callbacks:
    class_path: lightning.pytorch.callbacks.LearningRateMonitor
  # limit_val_batches: 0
  num_sanity_val_steps: 2
  log_every_n_steps: 25
