seed_everything: 42

model:
  class_path: models.jepa.JEPATrainer
  init_args:
    config:
      dim: 196
      slot_dim: ${.dim}
      alpha: 0.996
      n_target_blocks: 4
      scale: [0.1, 0.3]
      resolution: [224, 224]
      patch_size: 8
      enc_depth: 4
      enc_heads: 2
      pred_depth: 4
      pred_heads: 2
      loss: sinkhorn
    optimizer_config:
      start_lr: 2e-4
      ref_lr: 1e-3
      final_lr: 2e-6
      warmup_epochs: 10
      T_max: 100
      
data:
  class_path: dataset.image_dataset.DALIImageDataset
  init_args:
    root: "./data/walking_tours/test"
    batch_size: 64
    resolution: [224, 224]
    num_threads: 8

trainer:
  accumulate_grad_batches: 16
  precision: "bf16"
  max_epochs: 100
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "comp_jepa"
      log_model: False
      save_dir: ./lightning_logs
      # resume: "must"
      # id: xy7ta6ca 
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs:  5
        verbose: True
  limit_val_batches: 0
  num_sanity_val_steps: 0
  log_every_n_steps: 25


# ckpt_path: ./lightning_logs/comp_jepa/1pubo58y/checkpoints/epoch=94-step=18430.ckpt
